<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimalQuiz.Data\AnimalQuiz.Data.csproj" />
    <ProjectReference Include="..\AnimalQuiz.Models\AnimalQuiz.Models.csproj" />
  </ItemGroup>

</Project>
